text = input('Informe algo pelo teclado: ')
print('Informações sobre o que foi digitado')
print('O tipo primitivo é ', type(text))
print('É alfanumerico? ' , text.isalnum())
print('É alfabetico?', text.isalpha())
print('É ASCII?', text.isascii())
print('É Decimal?', text.isdecimal())
print('É Minusculo?', text.islower())
print('É Numerico?', text.isnumeric())
print('É Maiusculo?', text.isupper())